### ISSUE TITLE
do we need to declare sphinxcontrib as a namespace ? 

### ISSUE THREAD

**Issue by 12rambau** [sphinx-contrib/github-administration#38]
In many of this organization repositories there is a very specific __init__.py file in the sphinxcontrib folder like in https://github.com/sphinx-contrib/autoprogram/blob/master/sphinxcontrib/__init__.py

Is it compulsory or is it legacy code ? 

I would say having the folder is sufficient in itself, but I'm not sure.

**Comment by stephenfin** [comment]
These are all examples of [`pkg_resources`-style namespace packages](https://packaging.python.org/en/latest/guides/packaging-namespace-packages/#creating-a-namespace-package). I don't think it's needed now and we could rely on native namespace packages. I recently did this (on the second attempt) [in `sphinxcontrib-openapi`](https://github.com/sphinx-contrib/openapi/commit/344a58468cc989d41bcc5309753026732e6b30e2).

**Comment by stephenfin** [comment]
Probably worth pointing out that the docs explicitly state:

> [Setuptools](https://setuptools.pypa.io/en/latest/index.html) provides the [pkg_resources.declare_namespace](https://setuptools.readthedocs.io/en/latest/pkg_resources.html#namespace-package-support) function and the namespace_packages argument to setup(). Together these can be used to declare namespace packages. While this approach is no longer recommended, it is widely present in most existing namespace packages. If you are creating a new distribution within an existing namespace package that uses this method then it’s recommended to continue using this as the different methods are not cross-compatible and it’s not advisable to try to migrate an existing package.

However, I was able to migrate the package seemingly without issue so I'm not entirely sure what the issue with doing this is :thinking:

**Comment by 12rambau** [comment]
Perfect, 
I'll stick to native namespace packages for now then (it makes my life easier when packaging using pyproject.toml)

**Comment by stephenfin** [comment]
> However, I was able to migrate the package seemingly without issue so I'm not entirely sure what the issue with doing this is thinking

Just FYI, I looked into this further today and it turns out there's a repo describing the various failure cases of different namespace packages, which you can find [here](https://github.com/pypa/sample-namespace-packages/. In particular, [this doc](https://github.com/pypa/sample-namespace-packages/blob/master/table.md) is pretty useful. It covers the various failure modes of `pkutil`-style namespace packages and PEP-420 native namespace packages. fwict, if you solely install packages using `pip` in `python3.x` environment, mixing and matching should be a-okay. It does mean if you can expect users to have installed packages using `setup.py install` though, you might be in trouble. Again, just FYI.
