### ISSUE TITLE
Add ABC-sphinx-extension

### ISSUE THREAD

**Issue by wxtim** [sphinx-contrib/github-administration#45]
I'd like to join and add https://github.com/wxtim/abc-sphinx-extensions - typeset music for Sphinx

**Comment by dhellmann** [comment]
Welcome!

I have sent an invitation to join the org. Please close this ticket when you accept (I receive no notifications otherwise), or use it to let me know if you have any issues.

After you accept the invitation, you should have permission to move a repo into the org. You may need us to re-grant you admin access on that repo after the move, and you can use another ticket in this repo to ask for that if it is necessary.

**Comment by wxtim** [comment]
I've accepted - thank you!

@dhellmann  - can I have admin access to my repo - now "abc music" - although I may have a think about that, because abc is apt to be confusable with Abstract Base Classes in Python contexts.

**Comment by dhellmann** [comment]
@wxtim I updated your permissions on the repo to make you an admin. Please open a ticket here if you have any other issues. Thanks!
