### ISSUE TITLE
New sphinx extension

### ISSUE THREAD

**Issue by jennier0107** [sphinx-contrib/github-administration#59]
Hi, i want to add a new extension  [jennier0107/sphinxcontrib-del-marker: A sphinx plugin that enables embedding of HTML5 del](https://github.com/jennier0107/sphinxcontrib-del-marker) . Thanks

**Comment by dhellmann** [comment]
Welcome!

I have sent an invitation to join the org. Please close this ticket when you accept (I receive no notifications otherwise), or use it to let me know if you have any issues.

After you accept the invitation, you should have permission to move a repo into the org. You may need us to re-grant you admin access on that repo after the move, and you can use another ticket in this repo to ask for that if it is necessary.
