### ISSUE TITLE
Request to join the organization

### ISSUE THREAD

**Issue by quizoxis** [sphinx-contrib/github-administration#63]
Dear Sphinx Contrib team,
I have developed a Sphinx-contrib extension that I would like to be added to sphinx-contrib. 
I understand the initial step is to join the organization. I hereby request to join the organization.

Thank you,

Sincerely,
Jamshed Qureshi (quizoxis)

**Comment by dhellmann** [comment]
Welcome, quizoxis!

I have sent an invitation to join the org. Please close this ticket when you accept (I receive no notifications otherwise), or use it to let me know if you have any issues.

After you accept the invitation, you should have permission to move a repo into the org. You may need us to re-grant you admin access on that repo after the move, and you can use another ticket in this repo to ask for that if it is necessary.

**Comment by quizoxis** [comment]
Thank you Doug, I will be closing this issue.
Happy holidays 😊
